export const metadata = {
    title: "Shop",
    description: "Shop - Generated by create next app",
};

import TitlePage from "@/components/pagesComponents/TitlePage";

const Id = ({ params }) => {
    console.log(params);
    console.log(params.id);
    return (
        <>
            <TitlePage title="Id" />

            {params.id &&
                params.id.map((item) => {
                    return <p key={item.id}>{item}</p>;
                })}
        </>
    );
};

export default Id;
